import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SidebarMenu from '@/app/shared/layout/sidebar-menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <header></header>
          <article>{children}</article>
          <aside>
            <SidebarMenu />
          </aside>
          <footer></footer>
        </main>
      </body>
    </html>
  )
}
